// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SOTA_screen_init(void)
{
    ui_SOTA = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SOTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarOTA = lv_bar_create(ui_SOTA);
    lv_obj_set_width(ui_BarOTA, 480);
    lv_obj_set_height(ui_BarOTA, 64);
    lv_obj_set_align(ui_BarOTA, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarOTA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_BarOTA, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarOTA, lv_color_hex(0x8B8BFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarOTA, 128, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelOTA = lv_label_create(ui_SOTA);
    lv_obj_set_width(ui_LabelOTA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOTA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOTA, "OTA Update in Progess");
    lv_obj_set_style_text_font(ui_LabelOTA, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
