// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: TRGB-BC-Settings

#ifndef _TRGBBC_SETTINGS_UI_H
#define _TRGBBC_SETTINGS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

void ui_event_ScrSettings(lv_event_t * e);
extern lv_obj_t * ui_ScrSettings;
void ui_event_ScrSettButSleep(lv_event_t * e);
extern lv_obj_t * ui_ScrSettButSleep;
extern lv_obj_t * ui_ScrSettButSleepLabel;
void ui_event_ScrSettSliderBright(lv_event_t * e);
extern lv_obj_t * ui_ScrSettSliderBright;
extern lv_obj_t * ui_ScrSettSliderBrightLabel;
extern lv_obj_t * ui_ScrSettLabelClockDate;
extern lv_obj_t * ui_ScrSettLabelVersion;
void ui_event_ScrSettButReset(lv_event_t * e);
extern lv_obj_t * ui_ScrSettButReset;
extern lv_obj_t * ui_ScrSettButResetLabel;

void EvDeepSleep(lv_event_t * e);
void BrightChanged(lv_event_t * e);
void EvRestart(lv_event_t * e);

void ui_ScrSettings_screen_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
