// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include <ui/Screens/SOTA/ui.h>
#include <ui/ui_helpers.h>

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SOTA
lv_obj_t * ui_SOTA;
lv_obj_t * ui_BarOTA;
lv_obj_t * ui_LabelOTA;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_SOTA_updatePerc(uint8_t perc) {
	lv_bar_set_value(ui_BarOTA, perc, LV_ANIM_OFF);
}
