// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif


#include <lvgl.h>
#include "ui/font/font.h"
#include "ui/ui_helpers.h"


// SCREEN: ui_SOTA
void ui_SOTA_screen_init(void);
extern lv_obj_t * ui_SOTA;
extern lv_obj_t * ui_BarOTA;
extern lv_obj_t * ui_LabelOTA;


void ui_SOTA_updatePerc(uint8_t perc);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
