// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern lv_obj_t * ui_MainScreen;	// pointer to actual main screen

// Events

void statModeChanged(uint8_t mode);
void statModeNext(bool dir);

void resetStats();
void statsTimeMode(bool dir);

typedef enum {
	DSE_delayStandby = 1,
	DSE_toggleStandbyMode,
	DSE_switchOff
} UIDriveStateEvent;
void driveStateUpdate(const UIDriveStateEvent op);

void msgCppCB(bool ok);


#ifdef __cplusplus
} /*extern "C"*/
#endif
