// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: BC_ScreenWLAN


#include <lvgl.h>
#include "ui.h"
#include <ui/ui_helpers.h>

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SWLAN
void ui_event_SWLAN(lv_event_t * e);
lv_obj_t * ui_SWLAN;
lv_obj_t * ui_SWLANDropAP;
void ui_event_SWLANButConn(lv_event_t * e);
lv_obj_t * ui_SWLANButConn;
lv_obj_t * ui_SWLANButtCBLabel;
void ui_event_SWLANCBModeAP(lv_event_t * e);
lv_obj_t * ui_SWLANCBModeAP;
void ui_event_SWLANCBModeAutoAP(lv_event_t * e);
lv_obj_t * ui_SWLANCBModeAutoAP;
lv_obj_t * ui_SWLANLabelIP;
lv_obj_t * ui_SWLANPanel1;
void ui_event_SWLANTextPW(lv_event_t * e);
lv_obj_t * ui_SWLANTextPW;
void ui_event_SWLANLabelPW(lv_event_t * e);
lv_obj_t * ui_SWLANLabelPW;
lv_obj_t * ui_SWLANPanelPlacelholderQR;
void ui_event_SWLANRollerSSID(lv_event_t * e);
lv_obj_t * ui_SWLANRollerSSID;
lv_obj_t * ui_SWLANKeyB;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SWLAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_SWLANButConn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        WLANStoreNConn(e);
    }
}
void ui_event_SWLANCBModeAP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
    	WLANAPMode(lv_obj_get_state(target) & LV_STATE_CHECKED);
    }
}
void ui_event_SWLANCBModeAutoAP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WLANModeToggle(e);
    }
}
void ui_event_SWLANTextPW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_SWLANKeyB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_SWLANKeyB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_SWLANLabelPW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
    	lv_textarea_set_password_mode(ui_SWLANTextPW, !lv_textarea_get_password_mode(ui_SWLANTextPW));
    }
}
void ui_event_SWLANRollerSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EvSSIDRoller(e);
    }
}

///////////////////// SCREENS ////////////////////

