// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: BC_ScreenWLAN

#ifndef _BC_SCREENWLAN_UI_H
#define _BC_SCREENWLAN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include <ui/ui_helpers.h>
//#include <ui/ui_events.h>

// SCREEN: ui_SWLAN
void ui_SWLAN_screen_init(void);

void WLANModeToggle(lv_event_t * e);
void WLANAPMode(bool enable);
void EvSSIDRoller(lv_event_t * e);
void WLANStoreNConn(lv_event_t * e);

void ui_event_SWLAN(lv_event_t * e);
extern lv_obj_t * ui_SWLAN;
extern lv_obj_t * ui_SWLANDropAP;
void ui_event_SWLANButConn(lv_event_t * e);
extern lv_obj_t * ui_SWLANButConn;
extern lv_obj_t * ui_SWLANButtCBLabel;
void ui_event_SWLANCBModeAP(lv_event_t * e);
extern lv_obj_t * ui_SWLANCBModeAP;
void ui_event_SWLANCBModeAutoAP(lv_event_t * e);
extern lv_obj_t * ui_SWLANCBModeAutoAP;
extern lv_obj_t * ui_SWLANLabelIP;
extern lv_obj_t * ui_SWLANPanel1;
void ui_event_SWLANTextPW(lv_event_t * e);
extern lv_obj_t * ui_SWLANTextPW;
void ui_event_SWLANLabelPW(lv_event_t * e);
extern lv_obj_t * ui_SWLANLabelPW;
extern lv_obj_t * ui_SWLANPanelPlacelholderQR;
void ui_event_SWLANRollerSSID(lv_event_t * e);
extern lv_obj_t * ui_SWLANRollerSSID;
extern lv_obj_t * ui_SWLANKeyB;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
