// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ScreenChart

#include "ui.h"
#include <Arduino.h>

void EvButton1(lv_event_t * e)
{
	Serial.println("Chart Button 1 pressed!"); //TODO: Do something here
}

void EvButton2(lv_event_t * e)
{
	Serial.println("Chart Button 2 pressed!"); //TODO: Do something here
}
