#include "images.h"

const ext_img_desc_t images[21] = {
    { "SettingsIcon", &img_settings_icon },
    { "rr_icon_wifi", &img_rr_icon_wifi },
    { "rr_icon_gps", &img_rr_icon_gps },
    { "rr_icon_battery", &img_rr_icon_battery },
    { "rr_icon_turn", &img_rr_icon_turn },
    { "rr_icon_cadence", &img_rr_icon_cadence },
    { "rr_icon_power", &img_rr_icon_power },
    { "rr_icon_temp", &img_rr_icon_temp },
    { "rr_icon_height", &img_rr_icon_height },
    { "rr_icon_gradient", &img_rr_icon_gradient },
    { "rr_icon_heart", &img_rr_icon_heart },
    { "rr_icon_pause", &img_rr_icon_pause },
    { "rr_icon_state_stop", &img_rr_icon_state_stop },
    { "rr_icon_state_break", &img_rr_icon_state_break },
    { "rr_icon_state_power", &img_rr_icon_state_power },
    { "rr_icon_state_coasting", &img_rr_icon_state_coasting },
    { "rr_icon_turn_large", &img_rr_icon_turn_large },
    { "rr_icon_turn_64", &img_rr_icon_turn_64 },
    { "rr_icon_stopwatch", &img_rr_icon_stopwatch },
    { "rr_icon_clock", &img_rr_icon_clock },
    { "rr_icon_ruler", &img_rr_icon_ruler },
};