// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: BC_ScreenNavspj

#include <ui/Screens/SNavi/ui.h>
#include <ui/Screens/SNavi/ui_NaviCustFunc.h>
#include <ui/ui_helpers.h>

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SNavi
void ui_event_SNavi(lv_event_t * e);
lv_obj_t * ui_SNavi;
lv_obj_t * ui_SNavPanelStat;
lv_obj_t * ui_SNavLabelStreet;
lv_obj_t * ui_SNavArcSpeed;
lv_obj_t * ui_SNavImgNav;
lv_obj_t * ui_SNavBarNavDist;
lv_obj_t * ui_SNavLabelNavDist;
lv_obj_t * ui_SNavLabelSpeed;
lv_obj_t * ui_SNavBarHR;
lv_obj_t * ui_SNavLabenHR;
lv_obj_t * ui_SNavLabelCad;
lv_obj_t * ui_SNavBarBat;
lv_obj_t * ui_ImgButton1;

lv_obj_t * ui_SNavi_SBack;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SNavi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        ui_ScrNaviGoBack();
    }
}

///////////////////// SCREENS ////////////////////
