// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: BC_ScreenNavspj

#ifndef _BC_SCREENNAVSPJ_UI_H
#define _BC_SCREENNAVSPJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>
#include "ui/font/font.h"

#include "ui/ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SNavi
void ui_SNavi_screen_init(void);
void ui_event_SNavi(lv_event_t * e);
extern lv_obj_t * ui_SNavi;
extern lv_obj_t * ui_SNavPanelStat;
extern lv_obj_t * ui_SNavLabelStreet;
extern lv_obj_t * ui_SNavArcSpeed;
extern lv_obj_t * ui_SNavImgNav;
extern lv_obj_t * ui_SNavBarNavDist;
extern lv_obj_t * ui_SNavLabelNavDist;
extern lv_obj_t * ui_SNavLabelSpeed;
extern lv_obj_t * ui_SNavBarHR;
extern lv_obj_t * ui_SNavLabenHR;
extern lv_obj_t * ui_SNavLabelCad;
extern lv_obj_t * ui_SNavBarBat;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * ui_SNavi_SBack;

extern const lv_img_dsc_t* NavImgTable[];
extern const lv_img_dsc_t* Nav64ImgTable[];

void ui_SNavi_screen_init(void);

LV_IMG_DECLARE(nav_reserved)
LV_IMG_DECLARE(nav_straight )
LV_IMG_DECLARE(nav_start )
LV_IMG_DECLARE(nav_finish )
LV_IMG_DECLARE(nav_left45 )
LV_IMG_DECLARE(nav_left90 )
LV_IMG_DECLARE(nav_left135 )
LV_IMG_DECLARE(nav_right135 )
LV_IMG_DECLARE(nav_right90 )
LV_IMG_DECLARE(nav_right45 )
LV_IMG_DECLARE(nav_fork_r )
LV_IMG_DECLARE(nav_fork_l )
LV_IMG_DECLARE(nav_uturn )
LV_IMG_DECLARE(nav_Kreisel_3_3 )
LV_IMG_DECLARE(nav_nonav )


LV_IMG_DECLARE(nav_64_reserved)
LV_IMG_DECLARE(nav_64_straight )
LV_IMG_DECLARE(nav_64_start )
LV_IMG_DECLARE(nav_64_finish )
LV_IMG_DECLARE(nav_64_left45 )
LV_IMG_DECLARE(nav_64_left90 )
LV_IMG_DECLARE(nav_64_left135 )
LV_IMG_DECLARE(nav_64_right135 )
LV_IMG_DECLARE(nav_64_right90 )
LV_IMG_DECLARE(nav_64_right45 )
LV_IMG_DECLARE(nav_64_fork_r )
LV_IMG_DECLARE(nav_64_fork_l )
LV_IMG_DECLARE(nav_64_uturn )
LV_IMG_DECLARE(nav_64_Kreisel_3_3 )
LV_IMG_DECLARE(nav_64_nonav )

LV_FONT_DECLARE(ui_font_SchildGrot36);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
